load cloned world with doLoad() instead of addWorld() (fixes #2378)
Multiverse/Multiverse-Core pull request #2379
Opened 2020-08-13 22:16 UTC by rti

This pull request fixes #2378 

We actually can skip all the `WorldCreator` setup done by `addWorld()` as the cloned world is ready and just needs to be loaded. Just using `doLoad()` enables us to cleanly apply the copied properties, which is the intention of this patch.

2020-10-01 18:11 UTC, nicegamer7 requested changes
Thanks for the PR! Overall seems good. I just requested some style changes, nothing big.

2020-10-01 18:11 UTC, nicegamer7 commented on src/main/java/com/onarandombox/MultiverseCore/utils/WorldManager.java
> +            if(!saveWorldsConfig()) {
Please add a space after `if`.

2020-10-01 18:11 UTC, nicegamer7 commented on src/main/java/com/onarandombox/MultiverseCore/utils/WorldManager.java
> +            if(doLoad(newName)) {
Please add a space after `if`.

2020-10-01 18:11 UTC, nicegamer7 commented on src/main/java/com/onarandombox/MultiverseCore/utils/WorldManager.java
> +               Logging.fine("Succeeded at loading cloned world '" + newName + "'");
Just for consistency with the the modern MV codebase, this should be changed to from
```java
Logging.fine(...
```
to
```java
this.plugin.log(Level.FINE, ...
```

2020-10-01 18:22 UTC, nicegamer7 commented on src/main/java/com/onarandombox/MultiverseCore/utils/WorldManager.java
> +            worldsFromTheConfig.put(newName, newProps);
This is also a really small nitpick, but when referring to `worldsFromTheConfig`, please use `this.worldsFromTheConfig` as it makes it easier to see that it's an attribute of the class.

2020-10-01 19:21 UTC, rti commented
Thanks a lot for the review. I addressed your comments.

2020-10-01 19:25 UTC, rti commented
Not sure whether force-pushing was a good idea here. Github seems to be a bit confused now. Sorry. Hope that works for you.

2020-10-01 19:46 UTC, nicegamer7 requested changes

2020-10-01 19:46 UTC, nicegamer7 commented on src/main/java/com/onarandombox/MultiverseCore/utils/WorldManager.java
> +            newProps.copyValues(worldsFromTheConfig.get(oldName));
You missed a `this.` over here.

2020-10-01 19:47 UTC, nicegamer7 commented
Force pushing is fine.

2020-10-02 07:58 UTC, rti commented on src/main/java/com/onarandombox/MultiverseCore/utils/WorldManager.java
> +            newProps.copyValues(worldsFromTheConfig.get(oldName));
Oops. Thanks for pointing that out.

2020-10-02 08:14 UTC, benwoo1110 commented
Also just a note, usually it's good to create a new branch when making a PR instead of using master.

2020-10-02 08:45 UTC, rti commented
You are right. Would have been way cleaner. Though, I created my fork only to create this PR.

2020-10-02 08:46 UTC, rti commented
Hm, the travis build stopped while downloading something. Is there a way to re-trigger the build?

2020-10-03 12:01 UTC, benwoo1110 approved these changes

2020-10-03 14:27 UTC, nicegamer7 approved these changes

2020-10-03 14:33 UTC, nicegamer7 commented
I figured out how to trigger a restart 👍.

2020-10-05 04:29 UTC, merged

2020-10-05 04:29 UTC, dumptruckman commented
Awesome. Thank you for this!